### ISSUE TITLE
Problem accessing the DNS. (addr: live.twitch.tv): Unknown error occurred

### ISSUE THREAD

**Issue by Meistache** [wargio/Twitch-Streamer-Linux#44]
Hi,

I'm new to Twitch and using this script since my main desktop is been Linux (using Mint 17.1 Rebecca as distro) for a lot right now. But I'm unlucky since I'm getting the title error while running it. Stream key is right (I just hid it here pointing with $Where_to), and as far as it can occur to me there are no errors regarding ffmpeg or at least I don't believe so. Maybe I'm missing some conflicting flag here? If needed I'll post configuration file later (although the only things that I changed were $SUPRESS_OUTPUT - just returned it to false to get the output here, $WEBCAM to /dev/video0 - I'm using iphone as wireless webcam with gstreamer, and added a $SCRIPT_DIR var so it cd to it before starting from anywhere else).

So this is the console output:

------------------------------------------------------------------------------------------
Twitch Streamer for Linux (twitch_ffmpeg.sh)
Copyright (c) 2013 - 2014, Giovanni Dante Grazioli (deroad)

Using global twitch key located in home directory
[+] Click, with the mouse, on the Window that you want to Stream
 
 
Please setup the Audio Output to sink null (something like 'pavucontrol')
path comparing to:./Overlays/
no overlay is used cause path is not used or incorrect
You should be online! Check on http://twitch.tv/ (Press CTRL+C to stop)
 
where to is $Where_to
strim param ovl is 
strim param cfs is movie=/dev/video0:f=video4linux2,scale=320:240,setpts=PTS-STARTPTS[WebCam];[0:v]setpts=PTS-STARTPTS[Screen];[Screen][WebCam]overlay=0:0
 
 
ffmpeg version 1.2.6-7:1.2.6-1~trusty1 Copyright (c) 2000-2014 the FFmpeg developers
  built on Apr 26 2014 18:52:58 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
  configuration: --arch=amd64 --disable-stripping --enable-avresample --enable-pthreads --enable-runtime-cpudetect --extra-version='7:1.2.6-1~trusty1' --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --enable-bzlib --enable-libdc1394 --enable-libfreetype --enable-frei0r --enable-gnutls --enable-libgsm --enable-libmp3lame --enable-librtmp --enable-libopencv --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-vaapi --enable-vdpau --enable-libvorbis --enable-libvpx --enable-zlib --enable-gpl --enable-postproc --enable-libcdio --enable-x11grab --enable-libx264 --shlibdir=/usr/lib/x86_64-linux-gnu --enable-shared --disable-static
  libavutil      52. 18.100 / 52. 18.100
  libavcodec     54. 92.100 / 54. 92.100
  libavformat    54. 63.104 / 54. 63.104
  libavdevice    53.  5.103 / 53.  5.103
  libavfilter     3. 42.103 /  3. 42.103
  libswscale      2.  2.100 /  2.  2.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  2.100 / 52.  2.100
[x11grab @ 0xdc52c0] device: :0.0+354,497 -> display: :0.0 x: 354 y: 497 width: 301 height: 511
[x11grab @ 0xdc52c0] shared memory extension found
[x11grab @ 0xdc52c0] Estimating duration from bitrate, this may be inaccurate
Input #0, x11grab, from ':0.0+354,497':Twitch Streamer for Linux (twitch_ffmpeg.sh)
Copyright (c) 2013 - 2014, Giovanni Dante Grazioli (deroad)

Using global twitch key located in home directory
[+] Click, with the mouse, on the Window that you want to Stream
 
 
Please setup the Audio Output to sink null (something like 'pavucontrol')
path comparing to:./Overlays/
no overlay is used cause path is not used or incorrect
You should be online! Check on http://twitch.tv/ (Press CTRL+C to stop)
 
where to is $Where_to
strim param ovl is 
strim param cfs is movie=/dev/video0:f=video4linux2,scale=320:240,setpts=PTS-STARTPTS[WebCam];[0:v]setpts=PTS-STARTPTS[Screen];[Screen][WebCam]overlay=0:0
 
 
ffmpeg version 1.2.6-7:1.2.6-1~trusty1 Copyright (c) 2000-2014 the FFmpeg developers
  built on Apr 26 2014 18:52:58 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
  configuration: --arch=amd64 --disable-stripping --enable-avresample --enable-pthreads --enable-runtime-cpudetect --extra-version='7:1.2.6-1~trusty1' --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --enable-bzlib --enable-libdc1394 --enable-libfreetype --enable-frei0r --enable-gnutls --enable-libgsm --enable-libmp3lame --enable-librtmp --enable-libopencv --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-vaapi --enable-vdpau --enable-libvorbis --enable-libvpx --enable-zlib --enable-gpl --enable-postproc --enable-libcdio --enable-x11grab --enable-libx264 --shlibdir=/usr/lib/x86_64-linux-gnu --enable-shared --disable-static
  libavutil      52. 18.100 / 52. 18.100
  libavcodec     54. 92.100 / 54. 92.100
  libavformat    54. 63.104 / 54. 63.104
  libavdevice    53.  5.103 / 53.  5.103
  libavfilter     3. 42.103 /  3. 42.103
  libswscale      2.  2.100 /  2.  2.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  2.100 / 52.  2.100
[x11grab @ 0xdc52c0] device: :0.0+354,497 -> display: :0.0 x: 354 y: 497 width: 301 height: 511
[x11grab @ 0xdc52c0] shared memory extension found
[x11grab @ 0xdc52c0] Estimating duration from bitrate, this may be inaccurate
Input #0, x11grab, from ':0.0+354,497':
  Duration: N/A, start: 1426027091.594512, bitrate: 147658 kb/s
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 301x511, 147658 kb/s, 30 tbr, 1000k tbn, 30 tbc
[alsa @ 0xde0b00] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for  Input Stream #1.0 : stereo
Input #1, alsa, from 'pulse':
  Duration: N/A, start: 1426027091.615222, bitrate: 1536 kb/s
    Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
[video4linux2,v4l2 @ 0xdfe960] Estimating duration from bitrate, this may be inaccurate
Problem accessing the DNS. (addr: live.twitch.tv)
$Where_to: Unknown error occurred
 
Stopping Audio (Don't worry if you see errors here)
Failed to unload module: Module module-null-sink not loaded
Exit!

  Duration: N/A, start: 1426027091.594512, bitrate: 147658 kb/s
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 301x511, 147658 kb/s, 30 tbr, 1000k tbn, 30 tbc
[alsa @ 0xde0b00] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for  Input Stream #1.0 : stereo
Input #1, alsa, from 'pulse':
  Duration: N/A, start: 1426027091.615222, bitrate: 1536 kb/s
    Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
[video4linux2,v4l2 @ 0xdfe960] Estimating duration from bitrate, this may be inaccurate
Problem accessing the DNS. (addr: live.twitch.tv)
$Where_to: Unknown error occurred
 
Stopping Audio (Don't worry if you see errors here)
Failed to unload module: Module module-null-sink not loaded
Exit!

**Comment by wargio** [comment]
hi, you are using a version that i haven't tested (which i moved under the development branch). anyway, please redownload the script because i reverted back the repository to a tested version a few days ago. for the dns error, please, try to also change the twitch server, check the faq to know how to.

**Comment by Meistache** [comment]
Thanks for your answer and for your time! Well I had no luck with Twitch then I modified script to work with Hitbox. Gotcha, it works! (oh well I think I officially hate Twitch now...).

**Comment by wargio** [comment]
That's strange! unless twitch is blocked by your DNS. you should try to use google DNS or OpenDNS and try again.

**Comment by Meistache** [comment]
Just to update it, gave another shot on Twitch. Changing the server to live-mia made it. So this is nice now I have both options at least. But I cope with this about something blocking, just verified my account a couple times more to assure before testing, who knows...
