### ISSUE TITLE
Low FPS on Livecoding fork

### ISSUE THREAD

**Issue by wargio** [wargio/Twitch-Streamer-Linux#45]
They made a fork of ths script and the performance is low.

From @rodrigograca31

**Notes:**
* When its streaming, if I select a window that has the resolution of my screen it says: "[swscaler @ 0x1c4c1a0] Warning: data is not aligned! This can lead to a speedloss" but works, I read somewhere that was because the resolution was not a multiple of 8 (1366x768)....
* I'm getting very low FPS ... but I think that is because my internet velocity... right?
* The script should have a way to not use the webcam.... for now I've left it as "/dev/video1" because my webcam is at "/dev/video0" so it throws an error...
* And yes, I'm using a fork of this project, this one: https://github.com/cryptosan/Livecoding-Streamer-Linux

Some screenshots of the output I'm getting:
![](http://i.imgur.com/86V9xPi.png)
![](http://i.imgur.com/BhamPqv.png)

**Comment by rodrigograca31** [comment]
Here you can see my PC specs and my script configuration: 
![](http://i.imgur.com/ZCCnpMh.png)

* As you can see I have 24 frames (as low as possible so I don't overload the processor...)
* It looks like they only have 1 server...
* My quality is set to `ultrafast` so the problem is not here... 
* Yheaa, 6 threads, because I think I have a good CPU that can handle it... (i7, 2 ghz, 8 cores)(4 real cores, 4 virtual).
* I will try to make that change and report back.

**Comment by rodrigograca31** [comment]
Ok the low FPS problem seams to be a slow internet problem...
If I use `-save` it says 24 or 25 frames, but when I run it without the `-save` parameter it drops to 8,9 or 10 ...

About the `-threads $THREADS -thread_queue_size 512` change, did not work and stopped with an error:

`Option thread_queue_size (set the maximum number of queued packets from the demuxer) cannot be applied to output file rtmp://eumedia1.livecoding.tv:1935/livecodingtv/rodrigograca31?t=X -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for output file rtmp://eumedia1.livecoding.tv:1935/livecodingtv/rodrigograca31?t=X.
Error opening output files: Invalid argument`

I've changed it in the entire script...

**Comment by wargio** [comment]
ok, so it's the slow internet connection that affects the FPS. sorry for the CPU speculation, but i used this script on an old pc, and it was working pretty well, so i thought yours was older then mine xD

But if you have an i7, you should be ok ;)
Forget about -thread_queue_size you have a small problem with their server. your ping is too high to have a decent live session.

**Comment by rodrigograca31** [comment]
VPN will probably make it horse... since it will be another "hop"...
It's because in the end I'm using a mobile network...
