### ISSUE TITLE
Grab microphone to the audio stream

### ISSUE THREAD

**Issue by adamos42** [wargio/Twitch-Streamer-Linux#46]
I can stream my voice if I set in pavucontroll to stream the microphone to the line. Thats littlebit annoying because I can hear myself. Can the script grab the microphone and add to the audio?

**Comment by wargio** [comment]
Just use the 2 sink.

**Comment by adamos42** [comment]
Can you create a tutorial to how to use with your streamer script?

**Comment by wargio** [comment]
https://github.com/wargio/Twitch-Streamer-Linux#setup-audio-with-pavucontrol
