### ISSUE TITLE
Overlay Image

### ISSUE THREAD

**Issue by adamos42** [wargio/Twitch-Streamer-Linux#47]
It will be nice If the script able to handle the overlay image, the ffmpeg can handle but I don't know how to merge into the command. It has to be an other converting before stream?

```
ffmpeg -i input.mp4 -i image.png \
-filter_complex "[0:v][1:v] overlay=25:25:enable='between(t,0,20)'" \
-pix_fmt yuv420p -c:a copy \
output.mp4
```

**Comment by wargio** [comment]
change for the webcam stream 
` -vf "movie=$WEBCAM:f=video4linux2, scale=$WEBCAM_WH , setpts=PTS-STARTPTS [WebCam]; [in] setpts=PTS-STARTPTS [Screen]; [Screen][WebCam] overlay=$WEBCAM_XY [out]"`
with this
` -vf "movie=$WEBCAM:f=video4linux2, scale=$WEBCAM_WH , setpts=PTS-STARTPTS [WebCam]; movie=$MYIMAGE, scale=$IMAGE_WH [Watermark]; [in] setpts=PTS-STARTPTS [Screen]; [Screen][WebCam] overlay=$WEBCAM_XY [Image]; [Image][Watermark] overlay=$IMAGE_XY [out]"`

It should be right. i haven't tested it

Place under settings these options:
File name (add also the full path)
`MYIMAGE="myawesome.png"`
the output image width and heigth
`IMAGE_WH="320:240"`
position on the screen
`IMAGE_XY="10:10"`

**Comment by adamos42** [comment]
And without webcam?

**Comment by wargio** [comment]
place ` -vf "movie=$MYIMAGE, scale=$IMAGE_WH [Watermark]; [in] setpts=PTS-STARTPTS [Screen]; [Screen] [Watermark] overlay=$IMAGE_XY [out]"` after  `-threads $THREADS`

**Comment by adamos42** [comment]
Its working, now I have to make to change durring stream :P
